name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      #Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      #Give execute permission to mvnw
      - name: Make mvnw executable
        run: chmod +x mvnw

      #Build (compile)
      - name: Build with Maven (compile)
        run: ./mvnw clean compile

      #Run tests
      - name: Run tests
        run: ./mvnw test

      #Package application
      - name: Package application
        run: ./mvnw package -DskipTests

      #Upload JAR as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: library-system-jar
          path: target/*.jar
